:construction_worker: Update docs.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,6 +26,13 @@ jobs:
       - name: Extract tag and Details
         id: release
         run: |
+          # Check if the branch is 'main'
+          BRANCH_NAME=${GITHUB_REF_NAME}
+          if [ "$BRANCH_NAME" != "main" ]; then
+            echo "Error: Tag is not pushed on the 'main' branch. Current branch is '$BRANCH_NAME'."
+            exit 1
+          fi
+
           if [ "${{ github.ref_type }}" = "tag" ]; then
             TAG_NAME=${GITHUB_REF#refs/tags/}
             NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
